#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppCargo.Resource", IsApplication=true)]

namespace AppCargo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::AppCargo.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::AppCargo.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camionero = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cargoExpress = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int userIcon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int btnLUAHistorical = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int btnLUAModifyRegister = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnLUAPublishCargo = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int btnLUAPublishTravel = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int btnLUAReturn = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int btnMLogin = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int btnMLogout = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int btnMhAwardedCargoes = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int btnMhPerformedCargoes = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int btnMhReturn = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int btnMhSeeRank = 2131034135;
			
			// aapt resource value: 0x7f050025
			public const int btnPSRCarrier = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int btnPSRIngresar = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int btnPSRReturn = 2131034152;
			
			// aapt resource value: 0x7f050024
			public const int btnPSRUser = 2131034148;
			
			// aapt resource value: 0x7f05000d
			public const int chkMRecord = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int imgMView1 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int lblMPass = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int lblMRegister = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int lblMUser = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int lblMhMainTitle = 2131034132;
			
			// aapt resource value: 0x7f05001f
			public const int lblPSRRegister = 2131034143;
			
			// aapt resource value: 0x7f050026
			public const int lblPSRSelectUserMsg = 2131034150;
			
			// aapt resource value: 0x7f050021
			public const int lblPSRtypeOfUser = 2131034145;
			
			// aapt resource value: 0x7f05001a
			public const int lblPcDateList = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int lblPcNumOperation = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int lblPcOriginDestiny = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int lblPcTitleList = 2131034140;
			
			// aapt resource value: 0x7f050023
			public const int linearLayout1 = 2131034147;
			
			// aapt resource value: 0x7f050000
			public const int lstAc = 2131034112;
			
			// aapt resource value: 0x7f05001d
			public const int lstPcPerformed = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int psrSpc2 = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int spcPSR3 = 2131034146;
			
			// aapt resource value: 0x7f05000e
			public const int tblMLayout1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int tblMRow1 = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int txtLUAWelcomeUser = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int txtMPassword = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int txtMReset = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int txtMUserName = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int txtMWelcomeUser = 2131034119;
			
			// aapt resource value: 0x7f05001e
			public const int txtPSRWelcomeUser = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AwardedCargoes = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginUser = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainHistorical = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PerformedCargoes = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PerformedCargoesMain = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PreSelectionRegister = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Exit = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Login = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
