//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppCargoExpressEntities : DbContext
    {
        public AppCargoExpressEntities()
            : base("name=AppCargoExpressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<escalas> escalas { get; set; }
        public virtual DbSet<itinerarios> itinerarios { get; set; }
        public virtual DbSet<provincias> provincias { get; set; }
        public virtual DbSet<regiones> regiones { get; set; }
        public virtual DbSet<transacciones> transacciones { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<valoraciones> valoraciones { get; set; }
        public virtual DbSet<transporte> transporte { get; set; }
    }
}
