//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class escalas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public escalas()
        {
            this.transacciones = new HashSet<transacciones>();
        }
    
        public int id_escala { get; set; }
        public int id_itinerario { get; set; }
        public int ciudad_inicio { get; set; }
        public int ciudad_fin { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public System.DateTime fecha_llegada { get; set; }
        public string cancelada { get; set; }
    
        public virtual ciudades ciudades { get; set; }
        public virtual itinerarios itinerarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transacciones> transacciones { get; set; }
    }
}
