//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transporte
    {
        public int id_transporte { get; set; }
        public int id_usuario { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string anio { get; set; }
        public string color { get; set; }
        public string matricula { get; set; }
        public int tipo_transporte { get; set; }
        public decimal capacidad { get; set; }
        public string estado { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
