//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class valoraciones
    {
        public int id_valoracion { get; set; }
        public int id_usuario { get; set; }
        public int id_transacion { get; set; }
        public int valoracion { get; set; }
        public System.DateTime fecha_valoracion { get; set; }
    
        public virtual transacciones transacciones { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
